### ISSUE TITLE
Create server.py

### ISSUE THREAD

**Issue by gamemaker007** [NYUDevOpsPayments/payments#14]
**As a**   user
**I need**  a REST service 
**So that**  I can handle my payments platform.

**Assumptions:** 
* Root URL: /

**Acceptance Criteria:**
```
When I hit root url
Then I get information about the service.
```

**Comment by Willian-Zhang** [comment]
![image](https://user-images.githubusercontent.com/5165840/36701205-8edfd3e8-1b20-11e8-94fb-edf05db4b612.png)
![image](https://user-images.githubusercontent.com/5165840/36701214-93e7571c-1b20-11e8-9cbb-0582933be353.png)
