### ISSUE TITLE
Add to models.py : initialize a model

### ISSUE THREAD

**Issue by jimmyahacker** [NYUDevOpsPayments/payments#32]
**As a** developer 
**I need**  a function to initialize a model
**So that**  store all the payment information from a clean empty start state

**Assumptions:** 
* Function type: static method
* Function name: init_db
* Parameter: app, the server app that is bind to the model
* Return: void

**Acceptance Criteria:**
```
When init_db(app) is called
Then I should get an initialized model
```

**Comment by Willian-Zhang** [comment]
How is this different from #8 ?

**Comment by jimmyahacker** [comment]
This is actually the same. I looked into professor's code and think it is a must to separate the creating of models.py from the initialization of models @Willian-Zhang Thus, when #8 is solved. this should be closed, either.
I will just closes this issue
