### ISSUE TITLE
Use Pylint Review

### ISSUE THREAD

**Issue by gamemaker007** [NYUDevOpsPayments/payments#5]
**As a**   developer
**I need**  to use Pylint
**So that**  my code conforms to PEP8 Python standards

**Assumptions:** 
* I am using Python

**Acceptance Criteria:**
```
When I use Pylint
Then my code is very clean and easy to read and understand.
```

**Comment by Willian-Zhang** [comment]
Please see:
https://stackoverflow.com/questions/22448731/how-do-i-create-a-pylintrc-file

**Comment by Willian-Zhang** [comment]
sample file
https://github.com/PyCQA/pylint/blob/master/pylintrc
